# Generated by Django 4.0.5 on 2022-06-15 08:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='размер бокса в квадратных метрах')),
                ('month_rent_price', models.IntegerField(blank=True, verbose_name='стоимость аренды на месяц')),
                ('is_rented', models.BooleanField(blank=True, default=False, verbose_name='Бокс арендован')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text='ул. Манчестерская, д. 7, кв. 1', verbose_name='адрес')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None, verbose_name='телефон склада')),
                ('alias', models.CharField(blank=True, max_length=128, verbose_name='запоминающееся название')),
                ('first_square_meter_price', models.DecimalField(blank=True, decimal_places=2, default=599, max_digits=5, verbose_name='стоимость аренды за первый квадратный метр, руб/кв.м.')),
                ('rest_square_meters_price', models.DecimalField(blank=True, decimal_places=2, default=150, max_digits=5, verbose_name='стоимость аренды за все последующие квадратные метры кроме первого, руб/кв.м.')),
            ],
        ),
        migrations.CreateModel(
            name='BoxOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_term', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='срок аренды бокса в месяцах')),
                ('rent_start', models.DateField(auto_now_add=True, verbose_name='начало срока аренды бокса')),
                ('rent_end', models.DateField(null=True, verbose_name='конец срока аренды бокса')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='storage_app.box', verbose_name='бокс')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_orders', to=settings.AUTH_USER_MODEL, verbose_name='арендатор')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storage_app.storage', verbose_name='склад'),
        ),
    ]
