# Generated by Django 4.0.5 on 2022-06-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0002_storage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxorder',
            name='access_qr',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR-код для открытия'),
        ),
    ]
