# Generated by Django 4.0.5 on 2022-06-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0003_boxorder_access_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxorder',
            name='access_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код для открытия'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='alias',
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name='запоминающееся название'),
        ),
    ]
