# Generated by Django 4.0.5 on 2022-06-17 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0004_boxorder_access_code_alter_storage_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='floor',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='этаж'),
        ),
        migrations.AddField(
            model_name='box',
            name='height',
            field=models.FloatField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='высота'),
        ),
        migrations.AddField(
            model_name='box',
            name='length',
            field=models.FloatField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='длинна'),
        ),
        migrations.AddField(
            model_name='box',
            name='width',
            field=models.FloatField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='ширина'),
        ),
        migrations.AddField(
            model_name='storage',
            name='temperature',
            field=models.FloatField(blank=True, default=17, verbose_name='температура'),
        ),
    ]
