# Generated by Django 4.0.5 on 2022-06-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0006_storage_contacts_storage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='driving_directions',
            field=models.TextField(blank=True, help_text='После ул. Ленина поверните направо...', null=True, verbose_name='схема проезда'),
        ),
    ]
