# Generated by Django 4.0.5 on 2022-06-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0007_alter_storage_driving_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='month_rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='стоимость аренды на месяц'),
        ),
    ]
