# Generated by Django 4.0.5 on 2022-06-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0008_alter_box_month_rent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='month_rent_price',
            field=models.IntegerField(blank=True, verbose_name='стоимость аренды на месяц'),
        ),
    ]
