# Generated by Django 4.0.5 on 2022-06-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0009_alter_box_month_rent_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('send_at', models.DateField(auto_now_add=True, verbose_name='когда посетитель сайта оставил почту')),
            ],
            options={
                'verbose_name': 'почта',
                'verbose_name_plural': 'почты',
            },
        ),
    ]
