# Generated by Django 4.0.5 on 2022-06-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0010_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='send_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='когда посетитель сайта оставил почту'),
        ),
    ]
